language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.12.6
- 2.11.12
- 2.10.7
- 2.13.0-M4
script:
- sbt "++ ${TRAVIS_SCALA_VERSION}!" test
matrix:
  include:
  - scala: 2.12.6
    jdk: oraclejdk10
  - scala: 2.11.12
    env: JDK7_TEST
    script:
    - sbt "java++ 1.7" "++ ${TRAVIS_SCALA_VERSION}!" test
  - scala: 2.13.0-M5
    script:
    # TODO scalatest for Scala 2.13.0-M5
    - sbt "++ ${TRAVIS_SCALA_VERSION}!" compile
